# Generated by Django 4.2.5 on 2026-04-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('type', models.CharField(default='', max_length=255, verbose_name='商品类型')),
                ('title', models.CharField(default='', max_length=255, verbose_name='商品名称')),
                ('price', models.CharField(default='', max_length=255, verbose_name='商品价格')),
                ('buy_len', models.CharField(default='', max_length=255, verbose_name='商品销量')),
                ('img_src', models.CharField(default='', max_length=2555, verbose_name='商品图片')),
                ('name', models.CharField(default='', max_length=255, verbose_name='店铺名')),
                ('address', models.CharField(default='', max_length=255, verbose_name='地址')),
                ('isFressDelivery', models.CharField(default='', max_length=255, verbose_name='是/否包邮')),
                ('href', models.CharField(default='', max_length=2555, verbose_name='详情链接')),
                ('nameHref', models.CharField(default='', max_length=2555, verbose_name='店铺详情链接')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
